version: '3'
services:
    web:
        build: "./webapp"
        ports:
            - "8080:80"
    redis:
        image: "redis:alpine"
        ports: 
            - "6379:6379"
        volumes:
            - "/home/hewei/database/redis:/data"
    mongo:
        image: "mongo:3.6"
        ports:
            - "27017:27017"

